---
driver:
  name: vagrant
  provider: hyperv
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  name: winrm
  elevated: true

platforms:
  - name: windows2019
    driver:
      box: StefanScherer/windows_2019
      vm_hostname: test-posh

suites:
  - name: default
    run_list:
      - recipe[poshbot::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
